#Database configuration
quarkus.datasource.db-kind=${QURIUM_DATABASE:postgresql}
quarkus.datasource.username=${QURIUM_DATASOURCE_USERNAME:qurium}
quarkus.datasource.password=${QURIUM_DATASOURCE_PASSWORD:change-me}
quarkus.datasource.jdbc.url=${QURIUM_DATASOURCE_URL:jdbc:postgresql://localhost:5432/${QURIUM_DATASOURCE_DB:qurium}}

#Flyway configuration
quarkus.flyway.migrate-at-start=true
quarkus.flyway.clean-at-start=false
quarkus.flyway.locations=database/migrations

#Secret key for AES encryption and decryption
qurium.encryption.secret=${QURIUM_ENCRYPTION_SECRET}

quarkus.index-dependency.mapstruct.group-id=org.mapstruct