####
# This Dockerfile is used in order to build a container that runs the Quarkus application in JVM mode
#
# For day-to-day use, prefer the repository-root Dockerfile (docker compose build api).
#
# Before building this file, run ./mvnw package. The root .dockerignore excludes target/;
# use root Dockerfile for builds from source, or temporarily allow target/quarkus-app in .dockerignore.
#
# docker build -f src/main/docker/Dockerfile.jvm -t quarkus/api-jvm .
#
# Then run the container using:
#
# docker run -i --rm -p 8080:8080 quarkus/api-jvm
#
# If you want to include the debug port into your docker image
# you will have to expose the debug port (default 5005 being the default) like this :  EXPOSE 8080 5005.
# Additionally you will have to set -e JAVA_DEBUG=true and -e JAVA_DEBUG_PORT=*:5005
# when running the container
#
# Then run the container using :
#
# docker run -i --rm -p 8080:8080 quarkus/api-jvm
#
# Runtime: Eclipse Temurin 25 (JRE). Extra JVM flags: set JAVA_OPTS_APPEND at run time.
###
FROM eclipse-temurin:25-jre-alpine

ENV LANGUAGE='en_US:en' \
    JAVA_OPTS_APPEND='-Dquarkus.http.host=0.0.0.0 -Djava.util.logging.manager=org.jboss.logmanager.LogManager'

RUN addgroup -g 185 -S quarkus && adduser -u 185 -S quarkus -G quarkus

WORKDIR /deployments

# We make four distinct layers so if there are application changes the library layers can be re-used
COPY --chown=185:185 target/quarkus-app/lib/ /deployments/lib/
COPY --chown=185:185 target/quarkus-app/*.jar /deployments/
COPY --chown=185:185 target/quarkus-app/app/ /deployments/app/
COPY --chown=185:185 target/quarkus-app/quarkus/ /deployments/quarkus/

EXPOSE 8080
USER 185

ENTRYPOINT exec java $JAVA_OPTS_APPEND -jar /deployments/quarkus-run.jar

